language: cpp
compiler:
    - clang
    - gcc
os: linux
sudo: required
dist: trusty
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
install:
    # Install dependencies from apt
    - sudo apt-get install -qq libfreetype6-dev libsoil-dev libglew-dev libsfml-dev xorg-dev libgl1-mesa-dev libtclap-dev

    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

    # Install glfw (Trusty doesn't have glfw3)
    - wget https://github.com/glfw/glfw/archive/3.1.2.zip
    - unzip -qq 3.1.2.zip -d glfw
    - cd glfw/glfw-3.1.2
    - cmake . -G "Unix Makefiles"
    - sudo make install
    - cd ../..

    # Install glm (Trusty's version is too old)
    - wget https://github.com/g-truc/glm/archive/0.9.7.3.zip
    - unzip -qq 0.9.7.3.zip -d glm
    - cd glm/glm-0.9.7.3
    - cmake . -G "Unix Makefiles"
    - sudo make install
    - cd ../..

    # Install assimp (Trusty's version is too old)
    - wget https://github.com/assimp/assimp/archive/v3.2.zip
    - unzip -qq v3.2.zip -d assimp
    - cd assimp/assimp-3.2
    - cmake . -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DASSIMP_BUILD_TESTS=false
    - sudo make install
    - cd ../..

    # Install lua
    - curl -R -O http://www.lua.org/ftp/lua-5.3.2.tar.gz
    - tar zxf lua-5.3.2.tar.gz
    - cd lua-5.3.2

    # Patch the Makefile so it builds with -fPIC
    - cd src
    - wget https://gist.githubusercontent.com/jonathanbuchanan/bae5eb7d31ec629199e7/raw/37a298794800970321f86e3729f8cbf831ce392d/Makefile.patch --no-check-certificate
    - patch < Makefile.patch
    - cd ..

    - make linux
    - sudo make install
    - cd ..
script:
    - cmake . -G "Unix Makefiles"
    - make -j4
    - make test -j4
    - sudo make install

    # Build Feature
    - cd Sample\ Projects/Feature
    - cmake . -G "Unix Makefiles"
    - make
