# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonathan/Dev/sunglasses

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonathan/Dev/sunglasses

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/Dev/sunglasses/CMakeFiles /home/jonathan/Dev/sunglasses/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/Dev/sunglasses/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sunglasses

# Build rule for target.
sunglasses: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sunglasses
.PHONY : sunglasses

# fast build rule for target.
sunglasses/fast:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/build
.PHONY : sunglasses/fast

Audio/SunMusicObject.o: Audio/SunMusicObject.cpp.o
.PHONY : Audio/SunMusicObject.o

# target to build an object file
Audio/SunMusicObject.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunMusicObject.cpp.o
.PHONY : Audio/SunMusicObject.cpp.o

Audio/SunMusicObject.i: Audio/SunMusicObject.cpp.i
.PHONY : Audio/SunMusicObject.i

# target to preprocess a source file
Audio/SunMusicObject.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunMusicObject.cpp.i
.PHONY : Audio/SunMusicObject.cpp.i

Audio/SunMusicObject.s: Audio/SunMusicObject.cpp.s
.PHONY : Audio/SunMusicObject.s

# target to generate assembly for a file
Audio/SunMusicObject.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunMusicObject.cpp.s
.PHONY : Audio/SunMusicObject.cpp.s

Audio/SunSoundBufferStorage.o: Audio/SunSoundBufferStorage.cpp.o
.PHONY : Audio/SunSoundBufferStorage.o

# target to build an object file
Audio/SunSoundBufferStorage.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunSoundBufferStorage.cpp.o
.PHONY : Audio/SunSoundBufferStorage.cpp.o

Audio/SunSoundBufferStorage.i: Audio/SunSoundBufferStorage.cpp.i
.PHONY : Audio/SunSoundBufferStorage.i

# target to preprocess a source file
Audio/SunSoundBufferStorage.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunSoundBufferStorage.cpp.i
.PHONY : Audio/SunSoundBufferStorage.cpp.i

Audio/SunSoundBufferStorage.s: Audio/SunSoundBufferStorage.cpp.s
.PHONY : Audio/SunSoundBufferStorage.s

# target to generate assembly for a file
Audio/SunSoundBufferStorage.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunSoundBufferStorage.cpp.s
.PHONY : Audio/SunSoundBufferStorage.cpp.s

Audio/SunSoundListener.o: Audio/SunSoundListener.cpp.o
.PHONY : Audio/SunSoundListener.o

# target to build an object file
Audio/SunSoundListener.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunSoundListener.cpp.o
.PHONY : Audio/SunSoundListener.cpp.o

Audio/SunSoundListener.i: Audio/SunSoundListener.cpp.i
.PHONY : Audio/SunSoundListener.i

# target to preprocess a source file
Audio/SunSoundListener.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunSoundListener.cpp.i
.PHONY : Audio/SunSoundListener.cpp.i

Audio/SunSoundListener.s: Audio/SunSoundListener.cpp.s
.PHONY : Audio/SunSoundListener.s

# target to generate assembly for a file
Audio/SunSoundListener.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunSoundListener.cpp.s
.PHONY : Audio/SunSoundListener.cpp.s

Audio/SunSoundObject.o: Audio/SunSoundObject.cpp.o
.PHONY : Audio/SunSoundObject.o

# target to build an object file
Audio/SunSoundObject.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunSoundObject.cpp.o
.PHONY : Audio/SunSoundObject.cpp.o

Audio/SunSoundObject.i: Audio/SunSoundObject.cpp.i
.PHONY : Audio/SunSoundObject.i

# target to preprocess a source file
Audio/SunSoundObject.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunSoundObject.cpp.i
.PHONY : Audio/SunSoundObject.cpp.i

Audio/SunSoundObject.s: Audio/SunSoundObject.cpp.s
.PHONY : Audio/SunSoundObject.s

# target to generate assembly for a file
Audio/SunSoundObject.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Audio/SunSoundObject.cpp.s
.PHONY : Audio/SunSoundObject.cpp.s

Graphics/GUI/SunGUIItem.o: Graphics/GUI/SunGUIItem.cpp.o
.PHONY : Graphics/GUI/SunGUIItem.o

# target to build an object file
Graphics/GUI/SunGUIItem.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUIItem.cpp.o
.PHONY : Graphics/GUI/SunGUIItem.cpp.o

Graphics/GUI/SunGUIItem.i: Graphics/GUI/SunGUIItem.cpp.i
.PHONY : Graphics/GUI/SunGUIItem.i

# target to preprocess a source file
Graphics/GUI/SunGUIItem.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUIItem.cpp.i
.PHONY : Graphics/GUI/SunGUIItem.cpp.i

Graphics/GUI/SunGUIItem.s: Graphics/GUI/SunGUIItem.cpp.s
.PHONY : Graphics/GUI/SunGUIItem.s

# target to generate assembly for a file
Graphics/GUI/SunGUIItem.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUIItem.cpp.s
.PHONY : Graphics/GUI/SunGUIItem.cpp.s

Graphics/GUI/SunGUIItemMesh.o: Graphics/GUI/SunGUIItemMesh.cpp.o
.PHONY : Graphics/GUI/SunGUIItemMesh.o

# target to build an object file
Graphics/GUI/SunGUIItemMesh.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUIItemMesh.cpp.o
.PHONY : Graphics/GUI/SunGUIItemMesh.cpp.o

Graphics/GUI/SunGUIItemMesh.i: Graphics/GUI/SunGUIItemMesh.cpp.i
.PHONY : Graphics/GUI/SunGUIItemMesh.i

# target to preprocess a source file
Graphics/GUI/SunGUIItemMesh.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUIItemMesh.cpp.i
.PHONY : Graphics/GUI/SunGUIItemMesh.cpp.i

Graphics/GUI/SunGUIItemMesh.s: Graphics/GUI/SunGUIItemMesh.cpp.s
.PHONY : Graphics/GUI/SunGUIItemMesh.s

# target to generate assembly for a file
Graphics/GUI/SunGUIItemMesh.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUIItemMesh.cpp.s
.PHONY : Graphics/GUI/SunGUIItemMesh.cpp.s

Graphics/GUI/SunGUIMenu.o: Graphics/GUI/SunGUIMenu.cpp.o
.PHONY : Graphics/GUI/SunGUIMenu.o

# target to build an object file
Graphics/GUI/SunGUIMenu.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUIMenu.cpp.o
.PHONY : Graphics/GUI/SunGUIMenu.cpp.o

Graphics/GUI/SunGUIMenu.i: Graphics/GUI/SunGUIMenu.cpp.i
.PHONY : Graphics/GUI/SunGUIMenu.i

# target to preprocess a source file
Graphics/GUI/SunGUIMenu.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUIMenu.cpp.i
.PHONY : Graphics/GUI/SunGUIMenu.cpp.i

Graphics/GUI/SunGUIMenu.s: Graphics/GUI/SunGUIMenu.cpp.s
.PHONY : Graphics/GUI/SunGUIMenu.s

# target to generate assembly for a file
Graphics/GUI/SunGUIMenu.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUIMenu.cpp.s
.PHONY : Graphics/GUI/SunGUIMenu.cpp.s

Graphics/GUI/SunGUISystem.o: Graphics/GUI/SunGUISystem.cpp.o
.PHONY : Graphics/GUI/SunGUISystem.o

# target to build an object file
Graphics/GUI/SunGUISystem.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUISystem.cpp.o
.PHONY : Graphics/GUI/SunGUISystem.cpp.o

Graphics/GUI/SunGUISystem.i: Graphics/GUI/SunGUISystem.cpp.i
.PHONY : Graphics/GUI/SunGUISystem.i

# target to preprocess a source file
Graphics/GUI/SunGUISystem.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUISystem.cpp.i
.PHONY : Graphics/GUI/SunGUISystem.cpp.i

Graphics/GUI/SunGUISystem.s: Graphics/GUI/SunGUISystem.cpp.s
.PHONY : Graphics/GUI/SunGUISystem.s

# target to generate assembly for a file
Graphics/GUI/SunGUISystem.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/GUI/SunGUISystem.cpp.s
.PHONY : Graphics/GUI/SunGUISystem.cpp.s

Graphics/Shaders/SunShader.o: Graphics/Shaders/SunShader.cpp.o
.PHONY : Graphics/Shaders/SunShader.o

# target to build an object file
Graphics/Shaders/SunShader.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/Shaders/SunShader.cpp.o
.PHONY : Graphics/Shaders/SunShader.cpp.o

Graphics/Shaders/SunShader.i: Graphics/Shaders/SunShader.cpp.i
.PHONY : Graphics/Shaders/SunShader.i

# target to preprocess a source file
Graphics/Shaders/SunShader.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/Shaders/SunShader.cpp.i
.PHONY : Graphics/Shaders/SunShader.cpp.i

Graphics/Shaders/SunShader.s: Graphics/Shaders/SunShader.cpp.s
.PHONY : Graphics/Shaders/SunShader.s

# target to generate assembly for a file
Graphics/Shaders/SunShader.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/Shaders/SunShader.cpp.s
.PHONY : Graphics/Shaders/SunShader.cpp.s

Graphics/Shaders/SunShaderUniformObject.o: Graphics/Shaders/SunShaderUniformObject.cpp.o
.PHONY : Graphics/Shaders/SunShaderUniformObject.o

# target to build an object file
Graphics/Shaders/SunShaderUniformObject.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/Shaders/SunShaderUniformObject.cpp.o
.PHONY : Graphics/Shaders/SunShaderUniformObject.cpp.o

Graphics/Shaders/SunShaderUniformObject.i: Graphics/Shaders/SunShaderUniformObject.cpp.i
.PHONY : Graphics/Shaders/SunShaderUniformObject.i

# target to preprocess a source file
Graphics/Shaders/SunShaderUniformObject.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/Shaders/SunShaderUniformObject.cpp.i
.PHONY : Graphics/Shaders/SunShaderUniformObject.cpp.i

Graphics/Shaders/SunShaderUniformObject.s: Graphics/Shaders/SunShaderUniformObject.cpp.s
.PHONY : Graphics/Shaders/SunShaderUniformObject.s

# target to generate assembly for a file
Graphics/Shaders/SunShaderUniformObject.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/Shaders/SunShaderUniformObject.cpp.s
.PHONY : Graphics/Shaders/SunShaderUniformObject.cpp.s

Graphics/SunCamera.o: Graphics/SunCamera.cpp.o
.PHONY : Graphics/SunCamera.o

# target to build an object file
Graphics/SunCamera.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunCamera.cpp.o
.PHONY : Graphics/SunCamera.cpp.o

Graphics/SunCamera.i: Graphics/SunCamera.cpp.i
.PHONY : Graphics/SunCamera.i

# target to preprocess a source file
Graphics/SunCamera.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunCamera.cpp.i
.PHONY : Graphics/SunCamera.cpp.i

Graphics/SunCamera.s: Graphics/SunCamera.cpp.s
.PHONY : Graphics/SunCamera.s

# target to generate assembly for a file
Graphics/SunCamera.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunCamera.cpp.s
.PHONY : Graphics/SunCamera.cpp.s

Graphics/SunDirectionalShadowMapRenderingNode.o: Graphics/SunDirectionalShadowMapRenderingNode.cpp.o
.PHONY : Graphics/SunDirectionalShadowMapRenderingNode.o

# target to build an object file
Graphics/SunDirectionalShadowMapRenderingNode.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunDirectionalShadowMapRenderingNode.cpp.o
.PHONY : Graphics/SunDirectionalShadowMapRenderingNode.cpp.o

Graphics/SunDirectionalShadowMapRenderingNode.i: Graphics/SunDirectionalShadowMapRenderingNode.cpp.i
.PHONY : Graphics/SunDirectionalShadowMapRenderingNode.i

# target to preprocess a source file
Graphics/SunDirectionalShadowMapRenderingNode.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunDirectionalShadowMapRenderingNode.cpp.i
.PHONY : Graphics/SunDirectionalShadowMapRenderingNode.cpp.i

Graphics/SunDirectionalShadowMapRenderingNode.s: Graphics/SunDirectionalShadowMapRenderingNode.cpp.s
.PHONY : Graphics/SunDirectionalShadowMapRenderingNode.s

# target to generate assembly for a file
Graphics/SunDirectionalShadowMapRenderingNode.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunDirectionalShadowMapRenderingNode.cpp.s
.PHONY : Graphics/SunDirectionalShadowMapRenderingNode.cpp.s

Graphics/SunMesh.o: Graphics/SunMesh.cpp.o
.PHONY : Graphics/SunMesh.o

# target to build an object file
Graphics/SunMesh.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunMesh.cpp.o
.PHONY : Graphics/SunMesh.cpp.o

Graphics/SunMesh.i: Graphics/SunMesh.cpp.i
.PHONY : Graphics/SunMesh.i

# target to preprocess a source file
Graphics/SunMesh.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunMesh.cpp.i
.PHONY : Graphics/SunMesh.cpp.i

Graphics/SunMesh.s: Graphics/SunMesh.cpp.s
.PHONY : Graphics/SunMesh.s

# target to generate assembly for a file
Graphics/SunMesh.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunMesh.cpp.s
.PHONY : Graphics/SunMesh.cpp.s

Graphics/SunModel.o: Graphics/SunModel.cpp.o
.PHONY : Graphics/SunModel.o

# target to build an object file
Graphics/SunModel.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunModel.cpp.o
.PHONY : Graphics/SunModel.cpp.o

Graphics/SunModel.i: Graphics/SunModel.cpp.i
.PHONY : Graphics/SunModel.i

# target to preprocess a source file
Graphics/SunModel.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunModel.cpp.i
.PHONY : Graphics/SunModel.cpp.i

Graphics/SunModel.s: Graphics/SunModel.cpp.s
.PHONY : Graphics/SunModel.s

# target to generate assembly for a file
Graphics/SunModel.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunModel.cpp.s
.PHONY : Graphics/SunModel.cpp.s

Graphics/SunPointShadowMapRenderingNode.o: Graphics/SunPointShadowMapRenderingNode.cpp.o
.PHONY : Graphics/SunPointShadowMapRenderingNode.o

# target to build an object file
Graphics/SunPointShadowMapRenderingNode.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunPointShadowMapRenderingNode.cpp.o
.PHONY : Graphics/SunPointShadowMapRenderingNode.cpp.o

Graphics/SunPointShadowMapRenderingNode.i: Graphics/SunPointShadowMapRenderingNode.cpp.i
.PHONY : Graphics/SunPointShadowMapRenderingNode.i

# target to preprocess a source file
Graphics/SunPointShadowMapRenderingNode.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunPointShadowMapRenderingNode.cpp.i
.PHONY : Graphics/SunPointShadowMapRenderingNode.cpp.i

Graphics/SunPointShadowMapRenderingNode.s: Graphics/SunPointShadowMapRenderingNode.cpp.s
.PHONY : Graphics/SunPointShadowMapRenderingNode.s

# target to generate assembly for a file
Graphics/SunPointShadowMapRenderingNode.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunPointShadowMapRenderingNode.cpp.s
.PHONY : Graphics/SunPointShadowMapRenderingNode.cpp.s

Graphics/SunPrimitives.o: Graphics/SunPrimitives.cpp.o
.PHONY : Graphics/SunPrimitives.o

# target to build an object file
Graphics/SunPrimitives.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunPrimitives.cpp.o
.PHONY : Graphics/SunPrimitives.cpp.o

Graphics/SunPrimitives.i: Graphics/SunPrimitives.cpp.i
.PHONY : Graphics/SunPrimitives.i

# target to preprocess a source file
Graphics/SunPrimitives.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunPrimitives.cpp.i
.PHONY : Graphics/SunPrimitives.cpp.i

Graphics/SunPrimitives.s: Graphics/SunPrimitives.cpp.s
.PHONY : Graphics/SunPrimitives.s

# target to generate assembly for a file
Graphics/SunPrimitives.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunPrimitives.cpp.s
.PHONY : Graphics/SunPrimitives.cpp.s

Graphics/SunRenderer.o: Graphics/SunRenderer.cpp.o
.PHONY : Graphics/SunRenderer.o

# target to build an object file
Graphics/SunRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunRenderer.cpp.o
.PHONY : Graphics/SunRenderer.cpp.o

Graphics/SunRenderer.i: Graphics/SunRenderer.cpp.i
.PHONY : Graphics/SunRenderer.i

# target to preprocess a source file
Graphics/SunRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunRenderer.cpp.i
.PHONY : Graphics/SunRenderer.cpp.i

Graphics/SunRenderer.s: Graphics/SunRenderer.cpp.s
.PHONY : Graphics/SunRenderer.s

# target to generate assembly for a file
Graphics/SunRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunRenderer.cpp.s
.PHONY : Graphics/SunRenderer.cpp.s

Graphics/SunRenderingNode.o: Graphics/SunRenderingNode.cpp.o
.PHONY : Graphics/SunRenderingNode.o

# target to build an object file
Graphics/SunRenderingNode.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunRenderingNode.cpp.o
.PHONY : Graphics/SunRenderingNode.cpp.o

Graphics/SunRenderingNode.i: Graphics/SunRenderingNode.cpp.i
.PHONY : Graphics/SunRenderingNode.i

# target to preprocess a source file
Graphics/SunRenderingNode.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunRenderingNode.cpp.i
.PHONY : Graphics/SunRenderingNode.cpp.i

Graphics/SunRenderingNode.s: Graphics/SunRenderingNode.cpp.s
.PHONY : Graphics/SunRenderingNode.s

# target to generate assembly for a file
Graphics/SunRenderingNode.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunRenderingNode.cpp.s
.PHONY : Graphics/SunRenderingNode.cpp.s

Graphics/SunTextRenderer.o: Graphics/SunTextRenderer.cpp.o
.PHONY : Graphics/SunTextRenderer.o

# target to build an object file
Graphics/SunTextRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunTextRenderer.cpp.o
.PHONY : Graphics/SunTextRenderer.cpp.o

Graphics/SunTextRenderer.i: Graphics/SunTextRenderer.cpp.i
.PHONY : Graphics/SunTextRenderer.i

# target to preprocess a source file
Graphics/SunTextRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunTextRenderer.cpp.i
.PHONY : Graphics/SunTextRenderer.cpp.i

Graphics/SunTextRenderer.s: Graphics/SunTextRenderer.cpp.s
.PHONY : Graphics/SunTextRenderer.s

# target to generate assembly for a file
Graphics/SunTextRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunTextRenderer.cpp.s
.PHONY : Graphics/SunTextRenderer.cpp.s

Graphics/SunTexturedQuad.o: Graphics/SunTexturedQuad.cpp.o
.PHONY : Graphics/SunTexturedQuad.o

# target to build an object file
Graphics/SunTexturedQuad.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunTexturedQuad.cpp.o
.PHONY : Graphics/SunTexturedQuad.cpp.o

Graphics/SunTexturedQuad.i: Graphics/SunTexturedQuad.cpp.i
.PHONY : Graphics/SunTexturedQuad.i

# target to preprocess a source file
Graphics/SunTexturedQuad.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunTexturedQuad.cpp.i
.PHONY : Graphics/SunTexturedQuad.cpp.i

Graphics/SunTexturedQuad.s: Graphics/SunTexturedQuad.cpp.s
.PHONY : Graphics/SunTexturedQuad.s

# target to generate assembly for a file
Graphics/SunTexturedQuad.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Graphics/SunTexturedQuad.cpp.s
.PHONY : Graphics/SunTexturedQuad.cpp.s

Physics/GJKAlgorithm.o: Physics/GJKAlgorithm.cpp.o
.PHONY : Physics/GJKAlgorithm.o

# target to build an object file
Physics/GJKAlgorithm.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/GJKAlgorithm.cpp.o
.PHONY : Physics/GJKAlgorithm.cpp.o

Physics/GJKAlgorithm.i: Physics/GJKAlgorithm.cpp.i
.PHONY : Physics/GJKAlgorithm.i

# target to preprocess a source file
Physics/GJKAlgorithm.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/GJKAlgorithm.cpp.i
.PHONY : Physics/GJKAlgorithm.cpp.i

Physics/GJKAlgorithm.s: Physics/GJKAlgorithm.cpp.s
.PHONY : Physics/GJKAlgorithm.s

# target to generate assembly for a file
Physics/GJKAlgorithm.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/GJKAlgorithm.cpp.s
.PHONY : Physics/GJKAlgorithm.cpp.s

Physics/SunPhysicsCollider.o: Physics/SunPhysicsCollider.cpp.o
.PHONY : Physics/SunPhysicsCollider.o

# target to build an object file
Physics/SunPhysicsCollider.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsCollider.cpp.o
.PHONY : Physics/SunPhysicsCollider.cpp.o

Physics/SunPhysicsCollider.i: Physics/SunPhysicsCollider.cpp.i
.PHONY : Physics/SunPhysicsCollider.i

# target to preprocess a source file
Physics/SunPhysicsCollider.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsCollider.cpp.i
.PHONY : Physics/SunPhysicsCollider.cpp.i

Physics/SunPhysicsCollider.s: Physics/SunPhysicsCollider.cpp.s
.PHONY : Physics/SunPhysicsCollider.s

# target to generate assembly for a file
Physics/SunPhysicsCollider.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsCollider.cpp.s
.PHONY : Physics/SunPhysicsCollider.cpp.s

Physics/SunPhysicsColliderAABB.o: Physics/SunPhysicsColliderAABB.cpp.o
.PHONY : Physics/SunPhysicsColliderAABB.o

# target to build an object file
Physics/SunPhysicsColliderAABB.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderAABB.cpp.o
.PHONY : Physics/SunPhysicsColliderAABB.cpp.o

Physics/SunPhysicsColliderAABB.i: Physics/SunPhysicsColliderAABB.cpp.i
.PHONY : Physics/SunPhysicsColliderAABB.i

# target to preprocess a source file
Physics/SunPhysicsColliderAABB.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderAABB.cpp.i
.PHONY : Physics/SunPhysicsColliderAABB.cpp.i

Physics/SunPhysicsColliderAABB.s: Physics/SunPhysicsColliderAABB.cpp.s
.PHONY : Physics/SunPhysicsColliderAABB.s

# target to generate assembly for a file
Physics/SunPhysicsColliderAABB.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderAABB.cpp.s
.PHONY : Physics/SunPhysicsColliderAABB.cpp.s

Physics/SunPhysicsColliderMesh.o: Physics/SunPhysicsColliderMesh.cpp.o
.PHONY : Physics/SunPhysicsColliderMesh.o

# target to build an object file
Physics/SunPhysicsColliderMesh.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderMesh.cpp.o
.PHONY : Physics/SunPhysicsColliderMesh.cpp.o

Physics/SunPhysicsColliderMesh.i: Physics/SunPhysicsColliderMesh.cpp.i
.PHONY : Physics/SunPhysicsColliderMesh.i

# target to preprocess a source file
Physics/SunPhysicsColliderMesh.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderMesh.cpp.i
.PHONY : Physics/SunPhysicsColliderMesh.cpp.i

Physics/SunPhysicsColliderMesh.s: Physics/SunPhysicsColliderMesh.cpp.s
.PHONY : Physics/SunPhysicsColliderMesh.s

# target to generate assembly for a file
Physics/SunPhysicsColliderMesh.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderMesh.cpp.s
.PHONY : Physics/SunPhysicsColliderMesh.cpp.s

Physics/SunPhysicsColliderPlane.o: Physics/SunPhysicsColliderPlane.cpp.o
.PHONY : Physics/SunPhysicsColliderPlane.o

# target to build an object file
Physics/SunPhysicsColliderPlane.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderPlane.cpp.o
.PHONY : Physics/SunPhysicsColliderPlane.cpp.o

Physics/SunPhysicsColliderPlane.i: Physics/SunPhysicsColliderPlane.cpp.i
.PHONY : Physics/SunPhysicsColliderPlane.i

# target to preprocess a source file
Physics/SunPhysicsColliderPlane.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderPlane.cpp.i
.PHONY : Physics/SunPhysicsColliderPlane.cpp.i

Physics/SunPhysicsColliderPlane.s: Physics/SunPhysicsColliderPlane.cpp.s
.PHONY : Physics/SunPhysicsColliderPlane.s

# target to generate assembly for a file
Physics/SunPhysicsColliderPlane.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderPlane.cpp.s
.PHONY : Physics/SunPhysicsColliderPlane.cpp.s

Physics/SunPhysicsColliderSphere.o: Physics/SunPhysicsColliderSphere.cpp.o
.PHONY : Physics/SunPhysicsColliderSphere.o

# target to build an object file
Physics/SunPhysicsColliderSphere.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderSphere.cpp.o
.PHONY : Physics/SunPhysicsColliderSphere.cpp.o

Physics/SunPhysicsColliderSphere.i: Physics/SunPhysicsColliderSphere.cpp.i
.PHONY : Physics/SunPhysicsColliderSphere.i

# target to preprocess a source file
Physics/SunPhysicsColliderSphere.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderSphere.cpp.i
.PHONY : Physics/SunPhysicsColliderSphere.cpp.i

Physics/SunPhysicsColliderSphere.s: Physics/SunPhysicsColliderSphere.cpp.s
.PHONY : Physics/SunPhysicsColliderSphere.s

# target to generate assembly for a file
Physics/SunPhysicsColliderSphere.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsColliderSphere.cpp.s
.PHONY : Physics/SunPhysicsColliderSphere.cpp.s

Physics/SunPhysicsForce.o: Physics/SunPhysicsForce.cpp.o
.PHONY : Physics/SunPhysicsForce.o

# target to build an object file
Physics/SunPhysicsForce.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsForce.cpp.o
.PHONY : Physics/SunPhysicsForce.cpp.o

Physics/SunPhysicsForce.i: Physics/SunPhysicsForce.cpp.i
.PHONY : Physics/SunPhysicsForce.i

# target to preprocess a source file
Physics/SunPhysicsForce.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsForce.cpp.i
.PHONY : Physics/SunPhysicsForce.cpp.i

Physics/SunPhysicsForce.s: Physics/SunPhysicsForce.cpp.s
.PHONY : Physics/SunPhysicsForce.s

# target to generate assembly for a file
Physics/SunPhysicsForce.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsForce.cpp.s
.PHONY : Physics/SunPhysicsForce.cpp.s

Physics/SunPhysicsObject.o: Physics/SunPhysicsObject.cpp.o
.PHONY : Physics/SunPhysicsObject.o

# target to build an object file
Physics/SunPhysicsObject.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsObject.cpp.o
.PHONY : Physics/SunPhysicsObject.cpp.o

Physics/SunPhysicsObject.i: Physics/SunPhysicsObject.cpp.i
.PHONY : Physics/SunPhysicsObject.i

# target to preprocess a source file
Physics/SunPhysicsObject.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsObject.cpp.i
.PHONY : Physics/SunPhysicsObject.cpp.i

Physics/SunPhysicsObject.s: Physics/SunPhysicsObject.cpp.s
.PHONY : Physics/SunPhysicsObject.s

# target to generate assembly for a file
Physics/SunPhysicsObject.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsObject.cpp.s
.PHONY : Physics/SunPhysicsObject.cpp.s

Physics/SunPhysicsSimulator.o: Physics/SunPhysicsSimulator.cpp.o
.PHONY : Physics/SunPhysicsSimulator.o

# target to build an object file
Physics/SunPhysicsSimulator.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsSimulator.cpp.o
.PHONY : Physics/SunPhysicsSimulator.cpp.o

Physics/SunPhysicsSimulator.i: Physics/SunPhysicsSimulator.cpp.i
.PHONY : Physics/SunPhysicsSimulator.i

# target to preprocess a source file
Physics/SunPhysicsSimulator.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsSimulator.cpp.i
.PHONY : Physics/SunPhysicsSimulator.cpp.i

Physics/SunPhysicsSimulator.s: Physics/SunPhysicsSimulator.cpp.s
.PHONY : Physics/SunPhysicsSimulator.s

# target to generate assembly for a file
Physics/SunPhysicsSimulator.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsSimulator.cpp.s
.PHONY : Physics/SunPhysicsSimulator.cpp.s

Physics/SunPhysicsWorld.o: Physics/SunPhysicsWorld.cpp.o
.PHONY : Physics/SunPhysicsWorld.o

# target to build an object file
Physics/SunPhysicsWorld.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsWorld.cpp.o
.PHONY : Physics/SunPhysicsWorld.cpp.o

Physics/SunPhysicsWorld.i: Physics/SunPhysicsWorld.cpp.i
.PHONY : Physics/SunPhysicsWorld.i

# target to preprocess a source file
Physics/SunPhysicsWorld.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsWorld.cpp.i
.PHONY : Physics/SunPhysicsWorld.cpp.i

Physics/SunPhysicsWorld.s: Physics/SunPhysicsWorld.cpp.s
.PHONY : Physics/SunPhysicsWorld.s

# target to generate assembly for a file
Physics/SunPhysicsWorld.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Physics/SunPhysicsWorld.cpp.s
.PHONY : Physics/SunPhysicsWorld.cpp.s

SunButtonState.o: SunButtonState.cpp.o
.PHONY : SunButtonState.o

# target to build an object file
SunButtonState.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunButtonState.cpp.o
.PHONY : SunButtonState.cpp.o

SunButtonState.i: SunButtonState.cpp.i
.PHONY : SunButtonState.i

# target to preprocess a source file
SunButtonState.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunButtonState.cpp.i
.PHONY : SunButtonState.cpp.i

SunButtonState.s: SunButtonState.cpp.s
.PHONY : SunButtonState.s

# target to generate assembly for a file
SunButtonState.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunButtonState.cpp.s
.PHONY : SunButtonState.cpp.s

SunDirectionalLightObject.o: SunDirectionalLightObject.cpp.o
.PHONY : SunDirectionalLightObject.o

# target to build an object file
SunDirectionalLightObject.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunDirectionalLightObject.cpp.o
.PHONY : SunDirectionalLightObject.cpp.o

SunDirectionalLightObject.i: SunDirectionalLightObject.cpp.i
.PHONY : SunDirectionalLightObject.i

# target to preprocess a source file
SunDirectionalLightObject.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunDirectionalLightObject.cpp.i
.PHONY : SunDirectionalLightObject.cpp.i

SunDirectionalLightObject.s: SunDirectionalLightObject.cpp.s
.PHONY : SunDirectionalLightObject.s

# target to generate assembly for a file
SunDirectionalLightObject.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunDirectionalLightObject.cpp.s
.PHONY : SunDirectionalLightObject.cpp.s

SunGame.o: SunGame.cpp.o
.PHONY : SunGame.o

# target to build an object file
SunGame.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunGame.cpp.o
.PHONY : SunGame.cpp.o

SunGame.i: SunGame.cpp.i
.PHONY : SunGame.i

# target to preprocess a source file
SunGame.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunGame.cpp.i
.PHONY : SunGame.cpp.i

SunGame.s: SunGame.cpp.s
.PHONY : SunGame.s

# target to generate assembly for a file
SunGame.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunGame.cpp.s
.PHONY : SunGame.cpp.s

SunNode.o: SunNode.cpp.o
.PHONY : SunNode.o

# target to build an object file
SunNode.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunNode.cpp.o
.PHONY : SunNode.cpp.o

SunNode.i: SunNode.cpp.i
.PHONY : SunNode.i

# target to preprocess a source file
SunNode.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunNode.cpp.i
.PHONY : SunNode.cpp.i

SunNode.s: SunNode.cpp.s
.PHONY : SunNode.s

# target to generate assembly for a file
SunNode.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunNode.cpp.s
.PHONY : SunNode.cpp.s

SunObject.o: SunObject.cpp.o
.PHONY : SunObject.o

# target to build an object file
SunObject.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunObject.cpp.o
.PHONY : SunObject.cpp.o

SunObject.i: SunObject.cpp.i
.PHONY : SunObject.i

# target to preprocess a source file
SunObject.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunObject.cpp.i
.PHONY : SunObject.cpp.i

SunObject.s: SunObject.cpp.s
.PHONY : SunObject.s

# target to generate assembly for a file
SunObject.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunObject.cpp.s
.PHONY : SunObject.cpp.s

SunPointLightObject.o: SunPointLightObject.cpp.o
.PHONY : SunPointLightObject.o

# target to build an object file
SunPointLightObject.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunPointLightObject.cpp.o
.PHONY : SunPointLightObject.cpp.o

SunPointLightObject.i: SunPointLightObject.cpp.i
.PHONY : SunPointLightObject.i

# target to preprocess a source file
SunPointLightObject.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunPointLightObject.cpp.i
.PHONY : SunPointLightObject.cpp.i

SunPointLightObject.s: SunPointLightObject.cpp.s
.PHONY : SunPointLightObject.s

# target to generate assembly for a file
SunPointLightObject.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunPointLightObject.cpp.s
.PHONY : SunPointLightObject.cpp.s

SunScene.o: SunScene.cpp.o
.PHONY : SunScene.o

# target to build an object file
SunScene.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunScene.cpp.o
.PHONY : SunScene.cpp.o

SunScene.i: SunScene.cpp.i
.PHONY : SunScene.i

# target to preprocess a source file
SunScene.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunScene.cpp.i
.PHONY : SunScene.cpp.i

SunScene.s: SunScene.cpp.s
.PHONY : SunScene.s

# target to generate assembly for a file
SunScene.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/SunScene.cpp.s
.PHONY : SunScene.cpp.s

Utility.o: Utility.cpp.o
.PHONY : Utility.o

# target to build an object file
Utility.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Utility.cpp.o
.PHONY : Utility.cpp.o

Utility.i: Utility.cpp.i
.PHONY : Utility.i

# target to preprocess a source file
Utility.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Utility.cpp.i
.PHONY : Utility.cpp.i

Utility.s: Utility.cpp.s
.PHONY : Utility.s

# target to generate assembly for a file
Utility.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/Utility.cpp.s
.PHONY : Utility.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/main.cpp.s
.PHONY : main.cpp.s

pugixml.o: pugixml.cpp.o
.PHONY : pugixml.o

# target to build an object file
pugixml.cpp.o:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/pugixml.cpp.o
.PHONY : pugixml.cpp.o

pugixml.i: pugixml.cpp.i
.PHONY : pugixml.i

# target to preprocess a source file
pugixml.cpp.i:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/pugixml.cpp.i
.PHONY : pugixml.cpp.i

pugixml.s: pugixml.cpp.s
.PHONY : pugixml.s

# target to generate assembly for a file
pugixml.cpp.s:
	$(MAKE) -f CMakeFiles/sunglasses.dir/build.make CMakeFiles/sunglasses.dir/pugixml.cpp.s
.PHONY : pugixml.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sunglasses"
	@echo "... Audio/SunMusicObject.o"
	@echo "... Audio/SunMusicObject.i"
	@echo "... Audio/SunMusicObject.s"
	@echo "... Audio/SunSoundBufferStorage.o"
	@echo "... Audio/SunSoundBufferStorage.i"
	@echo "... Audio/SunSoundBufferStorage.s"
	@echo "... Audio/SunSoundListener.o"
	@echo "... Audio/SunSoundListener.i"
	@echo "... Audio/SunSoundListener.s"
	@echo "... Audio/SunSoundObject.o"
	@echo "... Audio/SunSoundObject.i"
	@echo "... Audio/SunSoundObject.s"
	@echo "... Graphics/GUI/SunGUIItem.o"
	@echo "... Graphics/GUI/SunGUIItem.i"
	@echo "... Graphics/GUI/SunGUIItem.s"
	@echo "... Graphics/GUI/SunGUIItemMesh.o"
	@echo "... Graphics/GUI/SunGUIItemMesh.i"
	@echo "... Graphics/GUI/SunGUIItemMesh.s"
	@echo "... Graphics/GUI/SunGUIMenu.o"
	@echo "... Graphics/GUI/SunGUIMenu.i"
	@echo "... Graphics/GUI/SunGUIMenu.s"
	@echo "... Graphics/GUI/SunGUISystem.o"
	@echo "... Graphics/GUI/SunGUISystem.i"
	@echo "... Graphics/GUI/SunGUISystem.s"
	@echo "... Graphics/Shaders/SunShader.o"
	@echo "... Graphics/Shaders/SunShader.i"
	@echo "... Graphics/Shaders/SunShader.s"
	@echo "... Graphics/Shaders/SunShaderUniformObject.o"
	@echo "... Graphics/Shaders/SunShaderUniformObject.i"
	@echo "... Graphics/Shaders/SunShaderUniformObject.s"
	@echo "... Graphics/SunCamera.o"
	@echo "... Graphics/SunCamera.i"
	@echo "... Graphics/SunCamera.s"
	@echo "... Graphics/SunDirectionalShadowMapRenderingNode.o"
	@echo "... Graphics/SunDirectionalShadowMapRenderingNode.i"
	@echo "... Graphics/SunDirectionalShadowMapRenderingNode.s"
	@echo "... Graphics/SunMesh.o"
	@echo "... Graphics/SunMesh.i"
	@echo "... Graphics/SunMesh.s"
	@echo "... Graphics/SunModel.o"
	@echo "... Graphics/SunModel.i"
	@echo "... Graphics/SunModel.s"
	@echo "... Graphics/SunPointShadowMapRenderingNode.o"
	@echo "... Graphics/SunPointShadowMapRenderingNode.i"
	@echo "... Graphics/SunPointShadowMapRenderingNode.s"
	@echo "... Graphics/SunPrimitives.o"
	@echo "... Graphics/SunPrimitives.i"
	@echo "... Graphics/SunPrimitives.s"
	@echo "... Graphics/SunRenderer.o"
	@echo "... Graphics/SunRenderer.i"
	@echo "... Graphics/SunRenderer.s"
	@echo "... Graphics/SunRenderingNode.o"
	@echo "... Graphics/SunRenderingNode.i"
	@echo "... Graphics/SunRenderingNode.s"
	@echo "... Graphics/SunTextRenderer.o"
	@echo "... Graphics/SunTextRenderer.i"
	@echo "... Graphics/SunTextRenderer.s"
	@echo "... Graphics/SunTexturedQuad.o"
	@echo "... Graphics/SunTexturedQuad.i"
	@echo "... Graphics/SunTexturedQuad.s"
	@echo "... Physics/GJKAlgorithm.o"
	@echo "... Physics/GJKAlgorithm.i"
	@echo "... Physics/GJKAlgorithm.s"
	@echo "... Physics/SunPhysicsCollider.o"
	@echo "... Physics/SunPhysicsCollider.i"
	@echo "... Physics/SunPhysicsCollider.s"
	@echo "... Physics/SunPhysicsColliderAABB.o"
	@echo "... Physics/SunPhysicsColliderAABB.i"
	@echo "... Physics/SunPhysicsColliderAABB.s"
	@echo "... Physics/SunPhysicsColliderMesh.o"
	@echo "... Physics/SunPhysicsColliderMesh.i"
	@echo "... Physics/SunPhysicsColliderMesh.s"
	@echo "... Physics/SunPhysicsColliderPlane.o"
	@echo "... Physics/SunPhysicsColliderPlane.i"
	@echo "... Physics/SunPhysicsColliderPlane.s"
	@echo "... Physics/SunPhysicsColliderSphere.o"
	@echo "... Physics/SunPhysicsColliderSphere.i"
	@echo "... Physics/SunPhysicsColliderSphere.s"
	@echo "... Physics/SunPhysicsForce.o"
	@echo "... Physics/SunPhysicsForce.i"
	@echo "... Physics/SunPhysicsForce.s"
	@echo "... Physics/SunPhysicsObject.o"
	@echo "... Physics/SunPhysicsObject.i"
	@echo "... Physics/SunPhysicsObject.s"
	@echo "... Physics/SunPhysicsSimulator.o"
	@echo "... Physics/SunPhysicsSimulator.i"
	@echo "... Physics/SunPhysicsSimulator.s"
	@echo "... Physics/SunPhysicsWorld.o"
	@echo "... Physics/SunPhysicsWorld.i"
	@echo "... Physics/SunPhysicsWorld.s"
	@echo "... SunButtonState.o"
	@echo "... SunButtonState.i"
	@echo "... SunButtonState.s"
	@echo "... SunDirectionalLightObject.o"
	@echo "... SunDirectionalLightObject.i"
	@echo "... SunDirectionalLightObject.s"
	@echo "... SunGame.o"
	@echo "... SunGame.i"
	@echo "... SunGame.s"
	@echo "... SunNode.o"
	@echo "... SunNode.i"
	@echo "... SunNode.s"
	@echo "... SunObject.o"
	@echo "... SunObject.i"
	@echo "... SunObject.s"
	@echo "... SunPointLightObject.o"
	@echo "... SunPointLightObject.i"
	@echo "... SunPointLightObject.s"
	@echo "... SunScene.o"
	@echo "... SunScene.i"
	@echo "... SunScene.s"
	@echo "... Utility.o"
	@echo "... Utility.i"
	@echo "... Utility.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pugixml.o"
	@echo "... pugixml.i"
	@echo "... pugixml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

